### ISSUE TITLE
Number of requests on OpenWeatherMap

### ISSUE THREAD

**Issue by 2hdlockness** [hangorazvan/pollution#1]
Hello
I installed the extension to have the air quality in compliments.
After a few hours of use I received a warning from OpenWeatherMap.
"Dear Customer,
Your OpenWeatherMap API key xxxxxxxxxxxxxxxxxxxxxxxxxxxxx is temporary blocked due to the continual sufficient exceeding of the calls per minute limit by performing 1025 requests within a minute but the limit for the Free account is 60 rpm."
Maybe a problem with the timer?
Have a good day

**Comment by hangorazvan** [comment]
No, the timer is OK, check your configuration and see in DevTools what make the calls.
